apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-image
  labels:
    app: broken-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-image
  template:
    metadata:
      labels:
        app: broken-image
    spec:
      containers:
        - name: app
          image: ghcr.io/louisguitton/does-not-exist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
